forge/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount_ember_app :frontend, to: "/"
end

forge/app/models/campaign.rb
# frozen_string_literal: true

# A campaign is the entire story of a game and all its contents
class Campaign < ApplicationRecord
  belongs_to :user

  has_many :setting_details
  has_many :chapters
  has_many :characters
  has_many :items
  has_many :notes, as: :notable

  # Custom Methods
  def chapter_display
    numbered_chapters = {}
    chapter_number = 1
    chapters.each do |chapter|
      numbered_chapters[chapter_number.to_s] = chapter.title
      chapter_number += 1
    end
    numbered_chapters
  end

  def setting_detail_display
    setting_details_full = {}
    setting_details.each do |detail|
      title = detail.title.capitalize
      setting_details_full[title] = detail.description
    end
    setting_details_full
  end

  def available_loot
    all_loot = []
    items.each do |item|
      item_data = {}
      item_data['item'] = item.name
      item_data['gold piece value'] = item.value
      item_data['details'] = item.details unless item.is_cash
      all_loot << item_data
    end
    all_loot
  end

  def gm_characters
    gm_characters = []
    characters.each do |character|
      gm_characters << character if character.user == character.campaign.user
    end
    gm_characters
  end

  def player_characters
    player_characters = []
    characters.each do |character|
      if character.user != character.campaign.user
        player_characters << character
      end
    end
    player_characters
  end
end

forge/app/models/character.rb
# frozen_string_literal: true

# A character is owned by a user, and represents a character in a campaign
class Character < ApplicationRecord
  belongs_to :user
  belongs_to :campaign

  has_many :blue_books
  has_many :items
  has_many :notes, as: :notable

  validates :user, uniqueness: {
    scope: :campaign,
    message: 'You already have a character.'
  }, if: :player_is_not_game_master

  def player_is_not_game_master
    campaign.user != user
  end
end

forge/app/controllers/campaigns_controller.rb
# frozen_string_literal: true

# Controls campaign actions
class CampaignsController < ApplicationController
  before_action :ensure_logged_in

  def index
    @campaigns = current_user.campaigns
  end

  def show
    @campaign = Campaign.find(params[:id])
    @chapters = @campaign.chapter_display
    @chapter = Chapter.new
    @player_characters = @campaign.player_characters
    @gm_characters = @campaign.gm_characters
  end

  def new
    @campaign = Campaign.new
  end

  def edit
    @campaign = Campaign.find(params[:id])
  end

  def create
    assign_campaign_attrs
    if @campaign.save
      flash[:alert] = 'Campaign successfully created!'
      redirect_to campaigns_url
    else
      render :new
      flash[:error] = 'There were errors in your campaign creation'
    end
  end

  def update
    assign_campaign_attrs
    if @campaign.save
      flash[:alert] = 'Campaign successfully updated!'
      redirect_to campaign_url(@campaign)
    else
      render :edit
      flash[:error] = 'There were errors in your campaign update'
    end
  end

  def destroy
    # TODO: Fill this in and add functionality
  end

  private

  def assign_campaign_attrs
    @campaign = params[:id] ? Campaign.find(params[:id]) : Campaign.new
    @campaign.user = current_user
    @campaign.title = params[:campaign][:title]
    @campaign.description = params[:campaign][:description]
  end
end

forge/app/views/campaigns/_form.html.erb
<%= form_for @campaign do |f| %>
  <div class='field'>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class='field'>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <%= f.submit 'Submit Form' %>
<% end %>

forge/app/views/campaigns/edit.html.erb
<h3>Edit Campaign</h3>
<%= render partial: 'form', locals: {campaign: @campaign} %>
<%= link_to "Back to #{@campaign.title}", campaign_path(@campaign) %>

forge/app/views/campaigns/index.html.erb
<h3 class='camapigns-header'>Your Campaigns</h3>
<%= link_to 'Start a new campaign?', new_campaign_path %>

<ul class='campaigns'>
  <% @campaigns.each do |campaign| %>
    <li><%= link_to campaign.title, campaign_path(campaign) %></li>
  <% end %>
</ul>

forge/app/views/campaigns/new.html.erb
<h3>New Campaign</h3>
<%= render partial: 'form', locals: {campaign: @campaign} %>

forge/app/views/campaigns/show.html.erb
<span class='header campaign-title'><%= @campaign.title %></span>
<div class='description-box'>
  <span class='header campaign-description'><%= link_to 'Campaign Details', campaign_setting_details_path(@campaign) %></span>
</div>

<!-- TODO: For each of these displays, post a message if they're empty -->
<!-- All the chapters for the campaign -->
<%= render partial: 'chapters/chapter_listing',
  locals: {
           campaign: @campaign,
           chapter: @chapter,
           chapters: @chapters
          }
%>

<!-- All the player characters for the campaign -->
<%= render partial: 'characters/party',
  locals: {
           player_characters: @player_characters,
           campaign: @campaign
          }
%>

<!-- All the npc characters for the campaign -->
<%= render partial: 'characters/npc_roster',
  locals: {
           gm_characters: @gm_characters,
           campaign: @campaign
          }
%>